---
name: 'YAML Linting'
on:
  push:
jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'configs'
          yamllint_strict: false
          yamllint_comment: false
